# TCL File Generated by Component Editor 21.1
# Thu Nov 09 03:10:16 MST 2023
# DO NOT MODIFY


# 
# HPS_Multi_PWM "HPS_Multi_PWM" v1.0
# Lucas Ritzdorf 2023.11.09.03:10:16
# Multi-PWM Controller
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module HPS_Multi_PWM
# 
set_module_property DESCRIPTION "Multi-PWM Controller"
set_module_property NAME HPS_Multi_PWM
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Peripherals
set_module_property AUTHOR "Lucas Ritzdorf"
set_module_property DISPLAY_NAME HPS_Multi_PWM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL HPS_Multi_PWM
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file common.vhd VHDL PATH ../hw/common.vhd
add_fileset_file hps_multi_pwm.vhd VHDL PATH ../hw/hps_multi_pwm.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter ADDR_WIDTH POSITIVE 1 ""
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 1
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE POSITIVE
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property ADDR_WIDTH DESCRIPTION ""
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter NUM_CHANNELS POSITIVE 1 ""
set_parameter_property NUM_CHANNELS DEFAULT_VALUE 1
set_parameter_property NUM_CHANNELS DISPLAY_NAME NUM_CHANNELS
set_parameter_property NUM_CHANNELS TYPE POSITIVE
set_parameter_property NUM_CHANNELS UNITS None
set_parameter_property NUM_CHANNELS ALLOWED_RANGES 1:2147483647
set_parameter_property NUM_CHANNELS DESCRIPTION ""
set_parameter_property NUM_CHANNELS HDL_PARAMETER true
add_parameter SYS_CLKs_sec POSITIVE 50000000
set_parameter_property SYS_CLKs_sec DEFAULT_VALUE 50000000
set_parameter_property SYS_CLKs_sec DISPLAY_NAME SYS_CLKs_sec
set_parameter_property SYS_CLKs_sec TYPE POSITIVE
set_parameter_property SYS_CLKs_sec UNITS None
set_parameter_property SYS_CLKs_sec ALLOWED_RANGES 1:2147483647
set_parameter_property SYS_CLKs_sec HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_address address Input "((addr_width-1)) - (0) + 1"
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pwms
# 
add_interface pwms conduit end
set_interface_property pwms associatedClock clock
set_interface_property pwms associatedReset ""
set_interface_property pwms ENABLED true
set_interface_property pwms EXPORT_OF ""
set_interface_property pwms PORT_NAME_MAP ""
set_interface_property pwms CMSIS_SVD_VARIABLES ""
set_interface_property pwms SVD_ADDRESS_GROUP ""

add_interface_port pwms out_channels out_channels Output NUM_CHANNELS

